title: "KiCad: Tu primera PCB de cero a fabricación"
description: "Tutorial completo paso a paso — esquemático, PCB, ruteo, agujeros, plano de tierra, logo, 3D, exportaciones (STEP/STL/DXF) y Gerbers."

# ✅ Modo recomendado en GitHub Pages:
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Si tu sitio es de proyecto:
url: "https://hubergiron.github.io"
baseurl: "/Kicad"

search_enabled: true
aux_links:
  "Repositorio en GitHub":
    - "https://github.com/hubergiron/Kicad"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
