title: "KiCad: Tu primera PCB de cero a fabricación"
description: "Tutorial completo paso a paso — esquemático, PCB, ruteo, agujeros, plano de tierra, logo, 3D, exportaciones (STEP/STL/DXF) y Gerbers."
theme: just-the-docs
# Si usas GitHub Pages (Settings → Pages), puedes publicar desde main /root o /docs
# y activar "GitHub Pages: Build and deployment".
# Si prefieres remote_theme (opcional), descomenta:
# remote_theme: just-the-docs/just-the-docs
# plugins:
#   - jekyll-remote-theme

search_enabled: true
aux_links:
  "Repositorio en GitHub":
    - "https://github.com/hubergiron/Kicad"

permalink: pretty

just_the_docs:
  # ...
  # incluir CSS adicional
  custom_css:
    - "assets/css/custom.css"
  footer_content: ""

# Navegación: usamos `nav_order` en el front matter de cada página.
# Puedes personalizar el footer o favicon agregando tus archivos en /assets.
